
#use_frameworks!


target 'InstaStream' do
pod 'FBSDKShareKit', '~> 4.36.0'
pod 'FBSDKLoginKit', '~> 4.36.0'
#pod 'FacebookLogin'
pod 'VideoCore/Swift', :git => 'https://github.com/maxcampolo/VideoCore.git', :branch => 'update_headers'
pod 'glm', :git => 'https://github.com/maxcampolo/glm.git'
#pod 'LFLiveKit'

 pod 'LFLiveKit', :path => '../LFLiveKit'
 pod 'GPUImage', :git => 'https://github.com/BradLarson/GPUImage.git', :commit => '167b0389bc6e9dc4bb0121550f91d8d5d6412c53'


  pod 'Fabric'
  pod 'Crashlytics'

#pod 'Toast-Swift', '~> 2.0.0'
#pod 'SwiftMessages'
#pod 'MBProgressHUD', '~> 1.1'
#pod 'Alamofire'
end
